### ISSUE TITLE
trouble decrypting on chatsecure

### ISSUE THREAD

**Issue by gkdr** [gkdr/lurch#46]
log from pidgin IRC channel:
```
<NwS> (00:07:24) lurch: lurch_bundle_create_session: failed to create a session from a bundle (-1002)
<NwS> (00:07:24) lurch: lurch_bundle_request_cb: failed to create a session (-1002)
[...]
<NwS> Can't see any msgs on ChatSecure :/ I can send from CS to pidgin but not the other way around
<NwS> Weird
<NwS> Same account on pidgin and chatsecure. Whatever I do on CS I can see on pidgin (for example if I send a Message with carbons I can see that msg on pidgin)
<NwS> Now, when I send from pidgin I don't see that msg on CS UNLESS that msg is more than 4 words (?)
<NwS> Now from account 2 that is only on pidgin, when I send to the account which is on CS + pidgin I can only receive it on pidgin. I received it once on CS but no idea why or how. Can't reproduce it lol
<NwS> Deleted the keys from the phone
<NwS> I did manage to get a few msgs that have more than 5 words in it until I send a msg or I make a mistake and try to get a shorter reply :/
<NwS> Ehm
<NwS> If I send a msg from pidgin Account1 (same account as phone) it seems to break the receiving part on CS
<NwS> In order to make it work again I must send a msg from CS
<NwS> And then post a msg from Account2(only pidgin) which contains more than 4 words :/
<NwS> I'm not sure what breaks it
<_riba> that "more than 4 words" thing is REALLY weird
<NwS> Yeah no idea why
<NwS> 4+ words work though lol
<NwS> less doesn't hah
```

Since I don't have an Iphone, any help debugging this is appreciated.

**Comment by dxerw** [comment]
Let's clear this up a bit.

Account1 = Pidgin + ChatSecure (with carbons)
Account2 = Pidgin


**Sending messages from Account1-P**
- Account2 receives everything fine
- Account1-CS won't show the sent message unless it is 17 characters long

**Sending messages from Account1-CS**
- Account2 receives everything fine
- Account1-P will show all the sent messages

**Sending messages from Account2**
- Account1-P receives everything fine
- Account1-CS if the message is 17 characters long it will receive it. BUT if you send a message from Account1-P it will stop receiving until you send another message from Chatsecure

**Comment by iNPUTmice** [comment]
FWIW I haven't tested the exact char count but I can confirm that ChatSecure does have problems receiving small messages. Same problem exists when sending from Conversations.

**Comment by dxerw** [comment]
@iNPUTmice do you know if @chrisballinger is aware of that issue?

**Comment by chrisballinger** [comment]
@dxerw I fixed it and plan to submit a release next week. Although we had code to process the new-style OMEMO auth tags, we still had an unnecessary length check on the payload left over.

https://github.com/ChatSecure/ChatSecure-iOS/commit/09b2a9247b2688c78e88217a594e6e485229eb29

**Comment by dxerw** [comment]
The new update fixed the characters problem but I still have the following problem:

**Sending messages from Account2**

- Account1-CS if you send a message from Account1-P it will stop receiving until you send another message from Chatsecure


PS: @chrisballinger when I send a msg from Pidgin which is the same account as CS, some msgs get the check sign (that the msg got delivered) while others don't. Any ideas why? All the msgs got delivered btw.

**Comment by chrisballinger** [comment]
By "Account1" do you mean the same JID on both CS and P?

**Comment by dxerw** [comment]
Yes. Account2 is the pidgin only account.

**Comment by chrisballinger** [comment]
We don't support MAM and barely support Carbons, so that's the problem.

**Comment by dxerw** [comment]
I thought Carbons were working 100% a few years now :/

Are you going to fix that anytime soon mate?

**Comment by chrisballinger** [comment]
They've worked in the past, but it's not included in my testing setup. We will be doing some work to better support multi-device once MAM is integrated but there's not an ETA. The general plan is XEP-0363, then OMEMO group chat, then MAM.

**Comment by gkdr** [comment]
Closing this old issue. I can't test it, but I heard it works. If it doesn't, please open a new issue.
